//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2022summer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        public int id { get; set; }
        public string number_seans { get; set; }
        public string zena { get; set; }
    }
}
