//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2022summer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> seans { get; set; }
        public Nullable<int> zal { get; set; }
        public Nullable<int> mesto { get; set; }
        public Nullable<int> zena { get; set; }
        public string film { get; set; }
        public string opisanie { get; set; }
        public string login_user { get; set; }
        public string fio_user { get; set; }
    }
}
